#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -lt 1 ]
then
	echo "REBOOT" > /dev/console
	sync
	reboot
elif [ "$SEEN" -gt 5 ]
then
	echo "FACTORY RESET" > /dev/console
	
	kill watchdog.sh 
	ps | grep essential/main.lua  | grep -v grep | awk '{print $1}' | xargs kill
	rm -rf /tmp/backup/* 
	sync 
	
	jffs2reset -y && reboot -f &
fi

return 0
