#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=10
BIN=/usr/sbin/telnet_mgr

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command $BIN start
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-16}
	procd_close_instance
}

stop_service() {
	$BIN stop
}
